#!/usr/bin/env python3
# generate_keys.py - 生成 BLS 密钥对
import sys
import os
sys.path.append('../services/ai')
from py_ecc.bls import G2ProofOfPossession as bls
import secrets

def generate_validator_keys(index):
    """生成单个验证者的BLS密钥对"""
    # BLS12-381 曲线的阶数
    CURVE_ORDER = 52435875175126190479447740508185965837690552500527637822603658699938581184513
    
    # 生成私钥
    sk = secrets.randbelow(CURVE_ORDER)
    
    # 从私钥派生公钥
    pk = bls.SkToPk(sk)
    
    return sk, pk

def write_to_env(keys, env_path='.env'):
    """将密钥写入 .env 文件"""
    # 读取现有的 .env 文件内容（如果存在）
    existing_lines = []
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            existing_lines = f.readlines()
    
    # 过滤掉旧的 VALIDATOR_*_SK 行
    filtered_lines = [line for line in existing_lines 
                      if not line.startswith('VALIDATOR_') or '_SK=' not in line]
    
    # 添加新的密钥
    new_lines = filtered_lines.copy()
    if new_lines and not new_lines[-1].endswith('\n'):
        new_lines.append('\n')
    
    new_lines.append('\n# Validator Keys (Generated by generate_keys.py)\n')
    for i, (sk, pk) in enumerate(keys, 1):
        new_lines.append(f'VALIDATOR_{i}_SK={sk}\n')
    
    # 写入文件
    with open(env_path, 'w') as f:
        f.writelines(new_lines)
    
    print(f"✅ Keys successfully written to {env_path}")

if __name__ == "__main__":
    print("="*60)
    print(" BLS Key Generation for EchoRank DVT Validators")
    print("="*60)
    print()
    
    # 为 3 个验证节点生成密钥
    keys = []
    for i in range(1, 4):
        sk, pk = generate_validator_keys(i)
        keys.append((sk, pk))
        print(f"✓ Generated keys for Validator {i}")
    
    print()
    print("="*60)
    print(" Writing keys to .env file...")
    print("="*60)
    print()
    
    # 确定 .env 文件路径（项目根目录）
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    env_path = os.path.join(project_root, '.env')
    
    # 写入 .env 文件
    write_to_env(keys, env_path)
    
    print()
    print("="*60)
    print(" ⚠️  IMPORTANT: Backup these keys securely!")
    print("="*60)
    print()
    print("Generated keys:")
    for i, (sk, pk) in enumerate(keys, 1):
        print(f"VALIDATOR_{i}_SK={sk}")
    print()
    print(f"📁 Keys saved to: {env_path}")